#!/usr/bin/env bash
# rebuild_index.sh — write Pretrain/data/index.txt from pod/MANIFEST,
# weighting sources that have shards present on THIS machine.
# Usage: bash pod/rebuild_index.sh [data_dir]   (default: Pretrain/data)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA_DIR="${1:-$REPO_ROOT/Pretrain/data}"
MANIFEST="$REPO_ROOT/pod/MANIFEST"

tmp="$(mktemp)"
echo "# auto-generated by pod/rebuild_index.sh $(date -u +%FT%TZ)" > "$tmp"

# For each manifest source, list its shards that exist (source_*.bin in
# data/vesperk/, or the exact file data/pretrain/<source>.bin), splitting
# the source weight equally among its present shards.
while read -r source weight; do
    [[ -z "${source}" || "${source}" == \#* ]] && continue
    shards=()
    while IFS= read -r f; do
        if [[ -s "$f" ]]; then
            shards+=("$f")
        else
            echo "# WARNING: skipping empty/missing shard $f" >&2
        fi
    done < <(
        { ls "$DATA_DIR/vesperk/${source}"_*.bin 2>/dev/null || true;
          ls "$DATA_DIR/pretrain/${source}.bin" 2>/dev/null || true;
          ls "$DATA_DIR/${source}.bin" 2>/dev/null || true; } | sort
    )
    n=${#shards[@]}
    [[ "$n" -eq 0 ]] && { echo "# (absent) $source" >> "$tmp"; continue; }
    per=$(python3 -c "print(float('$weight')/$n)")
    for s in "${shards[@]}"; do
        echo "$(realpath --relative-to="$DATA_DIR" "$s"), $per" >> "$tmp"
    done
done < "$MANIFEST"

mv "$tmp" "$DATA_DIR/index.txt"
echo "wrote $DATA_DIR/index.txt:"
cat "$DATA_DIR/index.txt"
